// <auto-generated />
namespace EducationSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ForAddFaculty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForAddFaculty));
        
        string IMigrationMetadata.Id
        {
            get { return "201912100701561_ForAddFaculty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
